# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4441b1ea651b15b8b9ab54ac519683ab"
name = "discount-disc"
application_url = "https://cloudflare-workers-app.radhouenekhalfa.workers.dev"
embedded = true

[app_proxy]
url = "https://cloudflare-workers-app.radhouenekhalfa.workers.dev/app/discounts"
subpath = "discounts"
prefix = "apps"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "write_app_proxy,read_app_proxy,read_discounts,write_discounts,read_price_rules,write_price_rules,read_products,write_products,read_customers,write_customers,read_orders,write_orders,read_analytics,read_inventory,read_locations,read_metaobjects,write_metaobjects"

[auth]
redirect_urls = [ 
  "https://cloudflare-workers-app.radhouenekhalfa.workers.dev/api/auth",
  "https://cloudflare-workers-app.radhouenekhalfa.workers.dev/auth/callback"
]
